title: "Aria Killebrew Bruehl"
author: "Aria Killebrew Bruehl"
description: "Portland, OR"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false # show article excerpts on the home page
show_frame: false # adds a gray frame to the site
show_sidebar: false # show a sidebar instead of the usual header
minimal: false # use a dark header

# Menu

navigation: # accepts {file, title, url, icon, sidebaricon}
  - { url: "Resume.pdf", title: "Resume" }
  - { file: "index.html", title: "Home" }

external: # shows a footer with social links - for available icons see fontawesome.com/icons
  - { title: Mail, icon: envelope, url: "mailto:ariadkb@gmail.com" }
  - {
      title: Github,
      icon: github,
      url: "https://github.com/ariakillebrewbruehl/",
    }
  - {
      title: LinkedIn,
      icon: linkedin,
      url: "https://www.linkedin.com/in/aria-killebrew-bruehl/",
    }

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
  - jekyll-feed
  - jemoji
